#ifndef ECHOPLUGINLIB_GLOBAL_H
#define ECHOPLUGINLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ECHOPLUGINLIB_LIBRARY)
#  define ECHOPLUGINLIB_EXPORT Q_DECL_EXPORT
#else
#  define ECHOPLUGINLIB_EXPORT Q_DECL_IMPORT
#endif

#endif // ECHOPLUGINLIB_GLOBAL_H
